# Generated by Django 2.2.3 on 2019-08-21 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoblocker',
            old_name='name',
            new_name='country',
        ),
    ]
